---
title: "02_modeling"
# output: html_document
---

# Environment

```{r}
library(skimr)
library(mgcv)
library(parallel)
library(parglm)
library(pROC)
library(ggplot2)
library(tibble)
library(dplyr)
library(feather)
library(broom)
library(htmlTable)


estudio_vacunas_t_final_selected <- readRDS(
  file = "/opt/datos_compartidos/vacunas_data/Rfiles/estudio_vacunas_t_final_selected.rds"
)
# metric performance
precision <- function(matrix) {
  # True positive
  tp <- matrix[2, 2]
  # false positive
  fp <- matrix[1, 2]
  return (tp / (tp + fp))
}

recall <- function(matrix) {
  # true positive
  tp <- matrix[2, 2]# false positive
  fn <- matrix[2, 1]
  return (tp / (tp + fn))
}

extract_coef_pval_OR <- function(model) {
  
  as.data.frame(tibble(term = names(model$coefficients),
                       estimate = model$coefficients,
                       std.error = sqrt(diag(vcov(model))),
                       statistic = model$coefficients / sqrt(diag(vcov(model))),
                       p.value = 2 * (1 - pnorm(abs(statistic))),
                       OR = round(exp(estimate),2),
                       OR_CI_lower = round(exp(estimate - 1.96 * std.error),2),
                       OR_CI_upper = round(exp(estimate + 1.96 * std.error),2)
  )
  )
} 
```

# logreg hosp_stay_bin

## Fitting the model

```{r}
print('glm')
print(Sys.time())
logreg_hosp_stay_bin <- glm(
  hosp_stay_bin ~ age_num + desc_sexo + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc + hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + pautas_covid,
  data =  estudio_vacunas_t_final_selected,
  family=binomial())
print(Sys.time())
```

## Odds ratio

```{r fig.height=16, fig.width=10}
coef_pval_df_hosp_stay_bin <- extract_coef_pval_OR(logreg_hosp_stay_bin)
# write.csv(coef_pval_df_hosp_stay_bin,'/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_hosp_stay_bin_v16mar.csv',col.names = F)
write.csv(coef_pval_df_hosp_stay_bin,'/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_hosp_stay_bin.csv',col.names = F)
htmlTable(coef_pval_df_hosp_stay_bin[,c("term","OR","OR_CI_lower","OR_CI_upper")])
```

## Forest Plot

```{r}
coef_pval_df_hosp_stay_bin2 <- 
  coef_pval_df_hosp_stay_bin %>% 
  mutate(orden = case_when(term == "age_num" ~ 1,
                           term == "desc_sexoHombre" ~ 2,
                           term == "asma" ~ 3,
                           term == "cardiopatia_isquemica" ~ 4,
                           term == "cirrosis_hepatica" ~ 5,
                           term == "diabetes" ~ 6,
                           term == "epoc" ~ 7,
                           term == "hepatopatia_cronica_excepto_cirrosis" ~ 8,
                           term == "hipertension" ~ 9,
                           term == "insuficiencia_cardiaca" ~ 10,
                           term == "insuficiencia_renal_cronica" ~ 11,
                           term == "vih" ~ 12,
                           term == "cancer_hematologico" ~ 13,
                           term == "cancer_organo_solido" ~ 14,
                           term == "pautas_covid1" ~ 15,
                           term == "pautas_covid2" ~ 16,
                           term == "pautas_covid3" ~ 17,
                           term == "pautas_covid4" ~ 18,
                           term == "(Intercept)" ~ 19,
                           TRUE ~ 999),
         term = case_when(term == "age_num" ~ "Edad (años)",
                          term == "desc_sexoHombre" ~ "Sexo: hombre",
                          term == "asma" ~ "Asma",
                          term == "cardiopatia_isquemica" ~ "Cardiopatía isquémica",
                          term == "cirrosis_hepatica" ~ "Cirrosis hepática",
                          term == "diabetes" ~ "Diabetes",
                          term == "epoc" ~ "EPOC",
                          term == "hepatopatia_cronica_excepto_cirrosis" ~ "Hepatopatía crónica (excepto cirrosis)",
                          term == "hipertension" ~ "Hipertensión",
                          term == "insuficiencia_cardiaca" ~ "Insuficiencia cardíaca",
                          term == "insuficiencia_renal_cronica" ~ "Insuficiencia renal crónica",
                          term == "vih" ~ "VIH +",
                          term == "cancer_hematologico" ~ "Cáncer hematológico",
                          term == "cancer_organo_solido" ~ "Cáncer de órgano sólido",
                          term == "pautas_covid1" ~ "1 dosis de vacuna",
                          term == "pautas_covid2" ~ "2 dosis de vacuna",
                          term == "pautas_covid3" ~ "3 dosis de vacuna",
                          term == "pautas_covid4" ~ "4 dosis de vacuna",
                          TRUE ~ term)) %>% 
  arrange(desc(orden)) %>% 
  select(-orden) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = factor(term, levels = term, ordered = TRUE))


ggplot(coef_pval_df_hosp_stay_bin2, 
       aes(x=term, y=OR, ymin=OR_CI_lower, ymax=OR_CI_upper)) +
  geom_hline(yintercept=1, colour = "blue", size=0.8, linetype="dotted") +
  geom_pointrange(alpha=0.7, shape=15) +
  geom_vline(xintercept=0, size=1.2) +
  scale_x_discrete(expand = expansion(add = c(1, 0.8))) + 
  scale_y_continuous(expand = expansion(add = c(0.1, 0.1))) +
  # scale_y_log10(
  #   limits=c(0.1, 4)
  #   ) +
  coord_flip() +
  labs(y="Odds Ratio", x=NULL)+
  ggtitle('Admisión Hospitalaria')+
  theme_minimal()

# Save the plot as a PNG file
ggsave("/opt/datos_compartidos/vacunas_data/figuras/coef_pval_df_hosp_stay_bin2.png", width = 6, height = 4, dpi = 300)
```


## Model Performance

```{r eval=FALSE, include=FALSE}
y_test <- estudio_vacunas_final_selected$hosp_stay_bin

predict <- predict(logreg_hosp_stay_bin, estudio_vacunas_final_selected, type = 'response')
# confusion matrix
table_mat <- table(y_test, predict > 0.85)
table_mat

accuracy <- sum(diag(table_mat)) / sum(table_mat)
accuracy

prec <- precision(table_mat)
prec

rec <- recall(table_mat)
rec

f1 <- 2 * ((prec * rec) / (prec + rec))
f1

#AUTOC plot

predicted_bin<-as.numeric(c(predict > 0.1))
rocobj <- roc(y_test, predicted_bin)

auc <- round(auc(y_test, predicted_bin),2)

#create ROC plot
ggroc(rocobj, colour = 'steelblue', size = 2) +
  ggtitle(paste0('ROC Curve ', '(AUC = ', auc, ')'))

metrics<-round(as.data.frame(rbind(accuracy,auc)),2)
metrics$metric<-rownames(metrics)
metrics$metric<-toupper(metrics$metric)

names(metrics)<-c('Value', 'Metric')

ggplot(data=metrics, aes(x=Metric, y=Value)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Value), vjust=1.6, color="white", size=3.5)+
  theme_minimal()
```

# logreg_icu_stay_bin

## Fitting the model

```{r}
print('glm')
print(Sys.time())
logreg_icu_stay_bin <- glm(
  icu_stay_bin ~ age_num + desc_sexo + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc + hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + pautas_covid,
  data =  estudio_vacunas_t_final_selected,
  family=binomial() )
print(Sys.time())
```
## Odds ratio

```{r fig.height=16, fig.width=10}
coef_pval_df_logreg_icu_stay_bin <- extract_coef_pval_OR(logreg_icu_stay_bin)
# write.csv(coef_pval_df_logreg_icu_stay_bin,'/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_logreg_icu_stay_bin_v16mar.csv',col.names = F)
write.csv(coef_pval_df_logreg_icu_stay_bin,'/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_logreg_icu_stay_bin.csv',col.names = F)
htmlTable(coef_pval_df_logreg_icu_stay_bin[,c("term","OR","OR_CI_lower","OR_CI_upper")])
```

## Forest Plot

```{r}
coef_pval_df_logreg_icu_stay_bin2 <- 
  coef_pval_df_logreg_icu_stay_bin %>% 
  mutate(orden = case_when(term == "age_num" ~ 1,
                           term == "desc_sexoHombre" ~ 2,
                           term == "asma" ~ 3,
                           term == "cardiopatia_isquemica" ~ 4,
                           term == "cirrosis_hepatica" ~ 5,
                           term == "diabetes" ~ 6,
                           term == "epoc" ~ 7,
                           term == "hepatopatia_cronica_excepto_cirrosis" ~ 8,
                           term == "hipertension" ~ 9,
                           term == "insuficiencia_cardiaca" ~ 10,
                           term == "insuficiencia_renal_cronica" ~ 11,
                           term == "vih" ~ 12,
                           term == "cancer_hematologico" ~ 13,
                           term == "cancer_organo_solido" ~ 14,
                           term == "pautas_covid1" ~ 15,
                           term == "pautas_covid2" ~ 16,
                           term == "pautas_covid3" ~ 17,
                           term == "pautas_covid4" ~ 18,
                           term == "(Intercept)" ~ 19,
                           TRUE ~ 999),
         term = case_when(term == "age_num" ~ "Edad (años)",
                          term == "desc_sexoHombre" ~ "Sexo: hombre",
                          term == "asma" ~ "Asma",
                          term == "cardiopatia_isquemica" ~ "Cardiopatía isquémica",
                          term == "cirrosis_hepatica" ~ "Cirrosis hepática",
                          term == "diabetes" ~ "Diabetes",
                          term == "epoc" ~ "EPOC",
                          term == "hepatopatia_cronica_excepto_cirrosis" ~ "Hepatopatía crónica (excepto cirrosis)",
                          term == "hipertension" ~ "Hipertensión",
                          term == "insuficiencia_cardiaca" ~ "Insuficiencia cardíaca",
                          term == "insuficiencia_renal_cronica" ~ "Insuficiencia renal crónica",
                          term == "vih" ~ "VIH +",
                          term == "cancer_hematologico" ~ "Cáncer hematológico",
                          term == "cancer_organo_solido" ~ "Cáncer de órgano sólido",
                          term == "pautas_covid1" ~ "1 dosis de vacuna",
                          term == "pautas_covid2" ~ "2 dosis de vacuna",
                          term == "pautas_covid3" ~ "3 dosis de vacuna",
                          term == "pautas_covid4" ~ "4 dosis de vacuna",
                          TRUE ~ term)) %>% 
  arrange(desc(orden)) %>% 
  select(-orden) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = factor(term, levels = term, ordered = TRUE),
         sobrepasa = case_when(OR_CI_upper > (sort(coef_pval_df_logreg_icu_stay_bin$OR_CI_upper, decreasing = TRUE)[2] + 10) ~ 1,
                               TRUE ~ 0),
         nuevo_OR_CI_upper = case_when(OR_CI_upper > (sort(coef_pval_df_logreg_icu_stay_bin$OR_CI_upper, decreasing = TRUE)[2] + 10) 
                                       ~ sort(coef_pval_df_logreg_icu_stay_bin$OR_CI_upper, decreasing = TRUE)[2] + 0.5,
                                       TRUE ~ OR_CI_upper))


ggplot(coef_pval_df_logreg_icu_stay_bin2, aes(x=term, y=OR, ymin=OR_CI_lower, ymax=nuevo_OR_CI_upper)) +
  geom_hline(yintercept=1,colour = "blue", size=0.8, linetype="dotted") +
  geom_pointrange(alpha=0.7, shape=15) +
  geom_text(data = coef_pval_df_logreg_icu_stay_bin2 %>% filter(sobrepasa == 1),
            aes(x=term, y=nuevo_OR_CI_upper),
            label = "▶", size = 3, family = "HiraKakuPro-W3", colour = "darkred") +
  # geom_point(data = coef_pval_df_logreg_icu_stay_bin2 %>% filter(sobrepasa = 1),
  #            shape = 17,
  #            ) +
  geom_vline(xintercept=0, size=1.2) +
  scale_x_discrete(expand = expansion(add = c(1, 0.8))) + 
  scale_y_continuous(expand = expansion(add = c(0.1, 0.05))) +
  # scale_y_log10(limits=c(0.1, 4)) +
  coord_flip() +
  labs(y="Odds Ratio", x=NULL)+
  ggtitle('Admisión UCI')+
  theme_minimal()

# Save the plot as a PNG file
ggsave("/opt/datos_compartidos/vacunas_data/figuras/coef_pval_df_logreg_icu_stay_bin2.png", width = 6, height = 4, dpi = 300)
```

## Model Performance

```{r eval=FALSE, include=FALSE}
y_test<-estudio_vacunas_final_selected$icu_stay_bin

predict <- predict(logreg_icu_stay_bin, estudio_vacunas_final_selected, type = 'response')
# confusion matrix
table_mat <- table(y_test, predict > 0.1)
table_mat

accuracy <- sum(diag(table_mat)) / sum(table_mat)
accuracy

prec <- precision(table_mat)
prec

rec <- recall(table_mat)
rec

f1 <- 2 * ((prec * rec) / (prec + rec))
f1

#AUTOC plot

predicted_bin<-as.numeric(c(predict > 0.3))
rocobj <- roc(y_test, predicted_bin)

auc <- round(auc(y_test, predicted_bin),2)

#create ROC plot
ggroc(rocobj, colour = 'steelblue', size = 2) +
  ggtitle(paste0('ROC Curve ', '(AUC = ', auc, ')'))

metrics<-round(as.data.frame(rbind(accuracy,auc)),2)
metrics$metric<-rownames(metrics)
metrics$metric<-toupper(metrics$metric)

names(metrics)<-c('Value', 'Metric')

ggplot(data=metrics, aes(x=Metric, y=Value)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Value), vjust=1.6, color="white", size=3.5)+
  theme_minimal()
```

# logreg_mortality

## Fitting the model

```{r}
print('glm')
print(Sys.time())
logreg_mortality <- glm(
  mortality30d ~ age_num + desc_sexo + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc + hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + pautas_covid,
  data =  estudio_vacunas_t_final_selected,
  family=binomial())
print(Sys.time())
```
## Odds ratio

```{r fig.height=16, fig.width=10}
coef_pval_df_logreg_mortality <- extract_coef_pval_OR(logreg_mortality)
# write.csv(coef_pval_df_logreg_mortality,'/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_logreg_mortality_v16mar.csv',col.names = F)
write.csv(coef_pval_df_logreg_mortality,'/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_logreg_mortality.csv',col.names = F)
htmlTable(coef_pval_df_logreg_mortality[,c("term","OR","OR_CI_lower","OR_CI_upper")])
```

## Forest Plot

```{r}
coef_pval_df_logreg_mortality2 <- 
  coef_pval_df_logreg_mortality %>% 
  mutate(orden = case_when(term == "age_num" ~ 1,
                           term == "desc_sexoHombre" ~ 2,
                           term == "asma" ~ 3,
                           term == "cardiopatia_isquemica" ~ 4,
                           term == "cirrosis_hepatica" ~ 5,
                           term == "diabetes" ~ 6,
                           term == "epoc" ~ 7,
                           term == "hepatopatia_cronica_excepto_cirrosis" ~ 8,
                           term == "hipertension" ~ 9,
                           term == "insuficiencia_cardiaca" ~ 10,
                           term == "insuficiencia_renal_cronica" ~ 11,
                           term == "vih" ~ 12,
                           term == "cancer_hematologico" ~ 13,
                           term == "cancer_organo_solido" ~ 14,
                           term == "pautas_covid1" ~ 15,
                           term == "pautas_covid2" ~ 16,
                           term == "pautas_covid3" ~ 17,
                           term == "pautas_covid4" ~ 18,
                           term == "(Intercept)" ~ 19,
                           TRUE ~ 999),
         term = case_when(term == "age_num" ~ "Edad (años)",
                          term == "desc_sexoHombre" ~ "Sexo: hombre",
                          term == "asma" ~ "Asma",
                          term == "cardiopatia_isquemica" ~ "Cardiopatía isquémica",
                          term == "cirrosis_hepatica" ~ "Cirrosis hepática",
                          term == "diabetes" ~ "Diabetes",
                          term == "epoc" ~ "EPOC",
                          term == "hepatopatia_cronica_excepto_cirrosis" ~ "Hepatopatía crónica (excepto cirrosis)",
                          term == "hipertension" ~ "Hipertensión",
                          term == "insuficiencia_cardiaca" ~ "Insuficiencia cardíaca",
                          term == "insuficiencia_renal_cronica" ~ "Insuficiencia renal crónica",
                          term == "vih" ~ "VIH +",
                          term == "cancer_hematologico" ~ "Cáncer hematológico",
                          term == "cancer_organo_solido" ~ "Cáncer de órgano sólido",
                          term == "pautas_covid1" ~ "1 dosis de vacuna",
                          term == "pautas_covid2" ~ "2 dosis de vacuna",
                          term == "pautas_covid3" ~ "3 dosis de vacuna",
                          term == "pautas_covid4" ~ "4 dosis de vacuna",
                          TRUE ~ term)) %>% 
  arrange(desc(orden)) %>% 
  select(-orden) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = factor(term, levels = term, ordered = TRUE))


ggplot(coef_pval_df_logreg_mortality2, aes(x=term, y=OR, ymin=OR_CI_lower, ymax=OR_CI_upper)) +
  geom_hline(yintercept=1,colour = "blue", size=0.8, linetype="dotted") +
  geom_pointrange(alpha=0.7, shape=15) +
  geom_vline(xintercept=0, size=1.2) +
  scale_x_discrete(expand = expansion(add = c(1, 0.8))) + 
  scale_y_continuous(expand = expansion(add = c(0.1, 0.1))) +
  # scale_y_log10(limits=c(0.1, 4)) +
  coord_flip() +
  labs(y="Odds Ratio", x=NULL)+
  ggtitle('Mortalidad')+
  theme_minimal()

# Save the plot as a PNG file
ggsave("/opt/datos_compartidos/vacunas_data/figuras/coef_pval_df_logreg_mortality2.png", width = 6, height = 4, dpi = 300)
```

## Model Performance

```{r eval=FALSE, include=FALSE}

y_test<-estudio_vacunas_final_selected$icu_stay_bin

predict <- predict(logreg_mortality, estudio_vacunas_final_selected, type = 'response')

# confusion matrix
table_mat <- table(y_test, predict > 0.1)
table_mat

accuracy <- sum(diag(table_mat)) / sum(table_mat)
accuracy

prec <- precision(table_mat)
prec

rec <- recall(table_mat)
rec

f1 <- 2 * ((prec * rec) / (prec + rec))
f1

#AUTOC plot

predicted_bin<-as.numeric(c(predict > 0.3))
rocobj <- roc(y_test, predicted_bin)

auc <- round(auc(y_test, predicted_bin),2)

#create ROC plot
ggroc(rocobj, colour = 'steelblue', size = 2) +
  ggtitle(paste0('ROC Curve ', '(AUC = ', auc, ')'))

metrics<-round(as.data.frame(rbind(accuracy,auc)),2)
metrics$metric<-rownames(metrics)
metrics$metric<-toupper(metrics$metric)

names(metrics)<-c('Value', 'Metric')

ggplot(data=metrics, aes(x=Metric, y=Value)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Value), vjust=1.6, color="white", size=3.5)+
  theme_minimal()
```


<!-- # survival model -->

<!-- ```{r} -->
<!-- #TODO evaluate efficiency -->
<!-- # event as numeric -->
<!-- estudio_vacunas_final_selected$estancia_hospitalaria<-as.numeric(estudio_vacunas_final_selected$estancia_hospitalaria) -->

<!-- res.cox <- coxph(Surv(estancia_hospitalaria_dias, estancia_hospitalaria) ~ DESC_SEXO + RESIDE_RESIDENCIA + GRUPO_7 + age + cancer + VIH + EPOC + ASMA + INSUF_CARDIACA + CARDIOPATÍA_ISQUÉMCIA + HEPATOPATIA_CRÓNICA + CIRROSIS + INSUF_RENAL_CRÓNICA + vac_groupB, data =  estudio_vacunas_final_selected) -->
<!-- ``` -->