---
title: "tabla2_20230221"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Libraries ----
library(forestmodel)
library(skimr)
library(mgcv)
library(parallel)
library(parglm)
library(pROC)
library(ggplot2)
library(feather)
library(broom)
library(htmlTable)
library(forestmodel)
library(gtsummary)
# library(tidyverse)
library(janitor)

## Function ----
extract_coef_pval_OR <- function(model) {
  
  as.data.frame(
    tibble(
      term = names(model$coefficients),
      estimate = model$coefficients,
      std.error = sqrt(diag(vcov(model))),
      statistic = model$coefficients / sqrt(diag(vcov(model))),
      p.value = 2 * (1 - pnorm(abs(statistic))),
      OR = round(exp(estimate),2),
      OR_CI_lower = round(exp(estimate - 1.96 * std.error),2),
      OR_CI_upper = round(exp(estimate + 1.96 * std.error),2)
    )
  )
} 

## Reading ----
estudio_vacunas_t_final_selected <- readRDS(
  file = "/opt/datos_compartidos/vacunas_data/Rfiles/toberemoved/estudio_vacunas_t_final_selected_v13feb.rds"
) %>%
  clean_names() %>% 
  mutate(
    infect_covid_first_date = case_when(
      stri_length(as.character(infect_covid_first_date)) %in% c(8, 10) ~ infect_covid_first_date
    ),
    hosp_stay_bin = as.numeric(hosp_stay_bin),
    infeccion_ingreso_dias = as.numeric(infeccion_ingreso_dias),
    mortality30d = case_when(
      (ymd(fec_fallecimiento) - infect_covid_first_date) < 31 ~ 1,
      T ~ 0
    )
  ) %>% 
  suppressWarnings()
```

```{r table 1}
## Ingreso hospitalario
t1 <- estudio_vacunas_t_final_selected %>%
  select(
    -c(
      cod_municipio,
      desc_municipio,
      fec_fallecimiento,
      infeccion_ingreso_dias
    )
  ) %>%
  mutate(
    age = as.numeric(age),
    estancia_hospitalaria_dias = as.numeric(estancia_hospitalaria_dias)
  ) %>%
  tbl_summary(
    by = hosp_stay_bin,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})"
    ),
    digits = list(
      age ~ 2
    )
  )

# %>% 
#   add_overall() %>% 
#   add_p()

## Mortalidad a los 30 días desde la fecha de la primera infección
t2 <- estudio_vacunas_t_final_selected %>%
  select(
    -c(
      cod_municipio,
      desc_municipio,
      fec_fallecimiento,
      infeccion_ingreso_dias
    )
  ) %>%
  mutate(
    age = as.numeric(age),
    estancia_hospitalaria_dias = as.numeric(estancia_hospitalaria_dias)
  ) %>%
  tbl_summary(
    by = mortality30d,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})"
    ),
    digits = list(
      age ~ 2
    )
  )

# %>% 
#   add_overall() %>% 
#   add_p()
```

```{r}
logreg_mortality <- glm(
  mortality30d ~ age_num + desc_sexo + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc + hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + pautas_covid + infecc_covid_num,
  data =  estudio_vacunas_t_final_selected,
  family = binomial()
)

coef_pval_df_logreg_mortality <- extract_coef_pval_OR(logreg_mortality)

write.table(
  coef_pval_df_logreg_mortality,
  sep = ",",
  "/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_logreg_mortality20230221.csv",
  col.names = F
  )

htmlTable(coef_pval_df_logreg_mortality[,c("term","OR","OR_CI_lower","OR_CI_upper")])

ggplot(coef_pval_df_logreg_mortality, aes(x=term, y=OR, ymin=OR_CI_lower, ymax=OR_CI_upper)) +
  geom_pointrange(alpha=0.7, shape=15) +
  geom_vline(xintercept=1) +
  scale_y_log10(limits=c(0.1, 4)) +
  coord_flip() +
  labs(y="Odds Ratio", x=NULL)+
  ggtitle('Mortalidad')+
  theme_minimal()

# Save the plot as a PNG file
ggsave("/opt/datos_compartidos/vacunas_data/figuras/coef_pval_df_logreg_mortality.png", width = 6, height = 4, dpi = 300)
```

