---
title: "02_modeling"
output: html_document
---

# Environment

```{r}
library(forestmodel)
library(skimr)
library(mgcv)
library(parallel)
library(parglm)
library(pROC)
library(ggplot2)
library(feather)
library(broom)
library(htmlTable)
library(forestmodel)
library(gtsummary)
# library(tidyverse)
library(janitor)

estudio_vacunas_t_final_selected <- readRDS(file = "/opt/datos_compartidos/vacunas_data/Rfiles/toberemoved/estudio_vacunas_t_final_selected_v13feb.rds")

estudio_vacunas_t_final_selected <- estudio_vacunas_t_final_selected %>% clean_names()

estudio_vacunas_t_final_selected <- estudio_vacunas_t_final_selected %>% 
  mutate(
    hosp_stay_bin = as.numeric(hosp_stay_bin),
    infeccion_ingreso_dias = as.numeric(infeccion_ingreso_dias),
    mortality30d = case_when(
      (ymd(fec_fallecimiento) - infect_covid_first_date) < 31 ~ 1,
      T ~ 0
    )
  ) %>% 
  suppressWarnings()

# metric performance

precision <- function(matrix) {
	# True positive
    tp <- matrix[2, 2]
	# false positive
    fp <- matrix[1, 2]
    return (tp / (tp + fp))
}

recall <- function(matrix) {
# true positive
    tp <- matrix[2, 2]# false positive
    fn <- matrix[2, 1]
    return (tp / (tp + fn))
}

extract_coef_pval_OR <- function(model) {

   as.data.frame(tibble(term = names(model$coefficients),
          estimate = model$coefficients,
          std.error = sqrt(diag(vcov(model))),
          statistic = model$coefficients / sqrt(diag(vcov(model))),
          p.value = 2 * (1 - pnorm(abs(statistic))),
          OR = round(exp(estimate),2),
          OR_CI_lower = round(exp(estimate - 1.96 * std.error),2),
          OR_CI_upper = round(exp(estimate + 1.96 * std.error),2)
   )
   )
} 
```

## Table 1 (table 2 in report)

```{r table 1}
str(estudio_vacunas_t_final_selected)

## Ingreso hospitalario
estudio_vacunas_t_final_selected %>%
  select(
    -c(
      cod_municipio,
      desc_municipio,
      fec_fallecimiento,
      infeccion_ingreso_dias
      )
    ) %>%
  mutate(
    age = as.numeric(age),
    estancia_hospitalaria_dias = as.numeric(estancia_hospitalaria_dias)
    ) %>%
  tbl_summary(
    by = hosp_stay_bin,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})"
      ),
    digits = list(
      age ~ 2
      )
    ) %>% 
  add_overall() %>% 
  add_p()

## Mortalidad a los 30 días desde la fecha de la primera infección
estudio_vacunas_t_final_selected %>%
  select(
    -c(
      cod_municipio,
      desc_municipio,
      fec_fallecimiento,
      infeccion_ingreso_dias
      )
    ) %>%
  mutate(
    age = as.numeric(age),
    estancia_hospitalaria_dias = as.numeric(estancia_hospitalaria_dias)
    ) %>%
  tbl_summary(
    by = mortality30d,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})"
      ),
    digits = list(
      age ~ 2
      )
    ) %>% 
  add_overall() %>% 
  add_p()
```


<!-- # logreg hosp_stay_bin -->

## Fitting the model

```{r}
print('glm')
print(Sys.time())
logreg_hosp_stay_bin <- glm(
  hosp_stay_bin ~ age_num + desc_sexo + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc + hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + pautas_covid + infecc_covid_num,
  data =  estudio_vacunas_t_final_selected,
  family=binomial())
print(Sys.time())
```

## Summary of the model
```{r}
summary(logreg_hosp_stay_bin)
```


## Odds ratio

```{r fig.height=16, fig.width=10}
coef_pval_df_hosp_stay_bin <- extract_coef_pval_OR(logreg_hosp_stay_bin)
write.csv(coef_pval_df_hosp_stay_bin,'/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_hosp_stay_bin.csv',col.names = F)
htmlTable(coef_pval_df_hosp_stay_bin[,c("term","OR","OR_CI_lower","OR_CI_upper")])
```

## Forest Plot

```{r}
ggplot(coef_pval_df_hosp_stay_bin, aes(x=term, y=OR, ymin=OR_CI_lower, ymax=OR_CI_upper)) +
 geom_pointrange(alpha=0.7, shape=15) +
 geom_vline(xintercept=1) +
 scale_y_log10(limits=c(0.1, 4)) +
 coord_flip() +
 labs(y="Odds Ratio", x=NULL)+
 ggtitle('Admisión Hospitalaria')+
 theme_minimal()

# Save the plot as a PNG file
ggsave("/opt/datos_compartidos/vacunas_data/figuras/coef_pval_df_hosp_stay_bin_v23feb.png", width = 6, height = 4, dpi = 300)
```


## Model Performance

```{r eval=FALSE, include=FALSE}
y_test <- estudio_vacunas_final_selected$hosp_stay_bin

predict <- predict(logreg_hosp_stay_bin, estudio_vacunas_final_selected, type = 'response')
# confusion matrix
table_mat <- table(y_test, predict > 0.85)
table_mat

accuracy <- sum(diag(table_mat)) / sum(table_mat)
accuracy

prec <- precision(table_mat)
prec

rec <- recall(table_mat)
rec

f1 <- 2 * ((prec * rec) / (prec + rec))
f1

#AUTOC plot

predicted_bin<-as.numeric(c(predict > 0.1))
rocobj <- roc(y_test, predicted_bin)

auc <- round(auc(y_test, predicted_bin),2)

#create ROC plot
ggroc(rocobj, colour = 'steelblue', size = 2) +
  ggtitle(paste0('ROC Curve ', '(AUC = ', auc, ')'))

metrics<-round(as.data.frame(rbind(accuracy,auc)),2)
metrics$metric<-rownames(metrics)
metrics$metric<-toupper(metrics$metric)

names(metrics)<-c('Value', 'Metric')

ggplot(data=metrics, aes(x=Metric, y=Value)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Value), vjust=1.6, color="white", size=3.5)+
  theme_minimal()
```

# logreg_icu_stay_bin

## Fitting the model

```{r}
print('glm')
print(Sys.time())
logreg_icu_stay_bin <- glm(
  icu_stay_bin ~ age_num + desc_sexo + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc + hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + pautas_covid + infecc_covid_num,
  data =  estudio_vacunas_t_final_selected,
  family=binomial() )
print(Sys.time())
```
## Odds ratio

```{r fig.height=16, fig.width=10}
coef_pval_df_logreg_icu_stay_bin <- extract_coef_pval_OR(logreg_icu_stay_bin)
write.csv(coef_pval_df_logreg_icu_stay_bin,'/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_logreg_icu_stay_bin.csv',col.names = F)
htmlTable(coef_pval_df_logreg_icu_stay_bin[,c("term","OR","OR_CI_lower","OR_CI_upper")])
```

## Forest Plot

```{r}
ggplot(coef_pval_df_logreg_icu_stay_bin, aes(x=term, y=OR, ymin=OR_CI_lower, ymax=OR_CI_upper)) +
 geom_pointrange(alpha=0.7, shape=15) +
 geom_vline(xintercept=1) +
 scale_y_log10(limits=c(0.1, 4)) +
 coord_flip() +
 labs(y="Odds Ratio", x=NULL)+
 ggtitle('Admisión UCI')+
 theme_minimal()

# Save the plot as a PNG file
ggsave("/opt/datos_compartidos/vacunas_data/figuras/coef_pval_df_logreg_icu_stay_bin.png", width = 6, height = 4, dpi = 300)
```

## Model Performance

```{r eval=FALSE, include=FALSE}
y_test<-estudio_vacunas_final_selected$icu_stay_bin

predict <- predict(logreg_icu_stay_bin, estudio_vacunas_final_selected, type = 'response')
# confusion matrix
table_mat <- table(y_test, predict > 0.1)
table_mat

accuracy <- sum(diag(table_mat)) / sum(table_mat)
accuracy

prec <- precision(table_mat)
prec

rec <- recall(table_mat)
rec

f1 <- 2 * ((prec * rec) / (prec + rec))
f1

#AUTOC plot

predicted_bin<-as.numeric(c(predict > 0.3))
rocobj <- roc(y_test, predicted_bin)

auc <- round(auc(y_test, predicted_bin),2)

#create ROC plot
ggroc(rocobj, colour = 'steelblue', size = 2) +
  ggtitle(paste0('ROC Curve ', '(AUC = ', auc, ')'))

metrics<-round(as.data.frame(rbind(accuracy,auc)),2)
metrics$metric<-rownames(metrics)
metrics$metric<-toupper(metrics$metric)

names(metrics)<-c('Value', 'Metric')

ggplot(data=metrics, aes(x=Metric, y=Value)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Value), vjust=1.6, color="white", size=3.5)+
  theme_minimal()
```

# logreg_mortality

## Fitting the model

```{r}
print('glm')
print(Sys.time())
logreg_mortality <- glm(
  mortality ~ age_num + desc_sexo + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc + hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido + pautas_covid + infecc_covid_num,
 data =  estudio_vacunas_t_final_selected,
 family=binomial())
print(Sys.time())
```
## Odds ratio

```{r fig.height=16, fig.width=10}
coef_pval_df_logreg_mortality <- extract_coef_pval_OR(logreg_mortality)
write.csv(coef_pval_df_logreg_mortality,'/opt/datos_compartidos/vacunas_data/tablas/coef_pval_df_logreg_mortality.csv',col.names = F)
htmlTable(coef_pval_df_logreg_mortality[,c("term","OR","OR_CI_lower","OR_CI_upper")])
```

## Forest Plot

```{r}
ggplot(coef_pval_df_logreg_mortality, aes(x=term, y=OR, ymin=OR_CI_lower, ymax=OR_CI_upper)) +
 geom_pointrange(alpha=0.7, shape=15) +
 geom_vline(xintercept=1) +
  scale_y_log10(limits=c(0.1, 4)) +
 coord_flip() +
 labs(y="Odds Ratio", x=NULL)+
 ggtitle('Mortalidad')+
 theme_minimal()

# Save the plot as a PNG file
ggsave("/opt/datos_compartidos/vacunas_data/figuras/coef_pval_df_logreg_mortality.png", width = 6, height = 4, dpi = 300)
```

## Model Performance

```{r eval=FALSE, include=FALSE}

y_test<-estudio_vacunas_final_selected$icu_stay_bin

predict <- predict(logreg_mortality, estudio_vacunas_final_selected, type = 'response')

# confusion matrix
table_mat <- table(y_test, predict > 0.1)
table_mat

accuracy <- sum(diag(table_mat)) / sum(table_mat)
accuracy

prec <- precision(table_mat)
prec

rec <- recall(table_mat)
rec

f1 <- 2 * ((prec * rec) / (prec + rec))
f1

#AUTOC plot

predicted_bin<-as.numeric(c(predict > 0.3))
rocobj <- roc(y_test, predicted_bin)

auc <- round(auc(y_test, predicted_bin),2)

#create ROC plot
ggroc(rocobj, colour = 'steelblue', size = 2) +
  ggtitle(paste0('ROC Curve ', '(AUC = ', auc, ')'))

metrics<-round(as.data.frame(rbind(accuracy,auc)),2)
metrics$metric<-rownames(metrics)
metrics$metric<-toupper(metrics$metric)

names(metrics)<-c('Value', 'Metric')

ggplot(data=metrics, aes(x=Metric, y=Value)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Value), vjust=1.6, color="white", size=3.5)+
  theme_minimal()
```


<!-- # survival model -->

<!-- ```{r} -->
<!-- #TODO evaluate efficiency -->
<!-- # event as numeric -->
<!-- estudio_vacunas_final_selected$estancia_hospitalaria<-as.numeric(estudio_vacunas_final_selected$estancia_hospitalaria) -->

<!-- res.cox <- coxph(Surv(estancia_hospitalaria_dias, estancia_hospitalaria) ~ DESC_SEXO + RESIDE_RESIDENCIA + GRUPO_7 + age + cancer + VIH + EPOC + ASMA + INSUF_CARDIACA + CARDIOPATÍA_ISQUÉMCIA + HEPATOPATIA_CRÓNICA + CIRROSIS + INSUF_RENAL_CRÓNICA + vac_groupB, data =  estudio_vacunas_final_selected) -->
<!-- ``` -->