---
title: "02b_modelling_subsets"
# output: html_document
---

# Environment

```{r}
library(magrittr)
library(tableone)
library(kableExtra)
library(summarytools)
library(vroom)
library(stringr)
library(stringi)
library(tidyr)
library(mgcv)
library(parglm)
library(tibble)
library(tidyverse)
library(lme4)
library(boot)
library(caTools)
library(caret)
library(pROC)
```

# Load Data

```{r}
estudio_vacunas_t_final_selected <- 
  readRDS("/opt/datos_compartidos/vacunas_data/Rfiles/estudio_vacunas_t_final_selected_manuscript.rds")
```

# Creating functions

```{r}
# metric performance
precision <- function(matrix) {
  # True positive
  tp <- matrix[2, 2]
  # false positive
  fp <- matrix[1, 2]
  return (tp / (tp + fp))
}

recall <- function(matrix) {
  # true positive
  tp <- matrix[2, 2]
  # false negative
  fn <- matrix[2, 1]
  return (tp / (tp + fn))
}

extract_coef_pval_OR <- function(model) {
  as.data.frame(tibble(
    term = names(model$coefficients),
    estimate = model$coefficients,
    std.error = sqrt(diag(vcov(model))),
    statistic = model$coefficients / sqrt(diag(vcov(model))),
    p.value = 2 * (1 - pnorm(abs(statistic))),
    OR = round(exp(estimate), 2),
    OR_CI_lower = round(exp(estimate - 1.96 * std.error), 2),
    OR_CI_upper = round(exp(estimate + 1.96 * std.error), 2)
  ))
}

set.seed(123)

# Create a function to split the data with balanced outcome percentages
balanced_split <- function(data, outcome_var, split_ratio) {
  unique_outcomes <- unique(data[[outcome_var]])
  train_data <- data.frame()
  test_data <- data.frame()
  
  # Iterate over each unique outcome and split the data
  for (outcome in unique_outcomes) {
    subset_data <- data[data[[outcome_var]] == outcome, ]
    split <- sample(nrow(subset_data), size = round(nrow(subset_data) * split_ratio))
    train_subset <- subset_data[split, ]
    test_subset <- subset_data[-split, ]
    train_data <- rbind(train_data, train_subset)
    test_data <- rbind(test_data, test_subset)
  }
  
  return(list(train_data = train_data, test_data = test_data))
}

# Define the evaluation metric
f1_score <- function(data, lev = NULL, model = NULL) {
  predictions <- factor(ifelse(data$obs == lev[1], lev[1], lev[2]), levels = lev)
  reference <- factor(data$obs, levels = lev)
  
  f1 <- F_meas(predictions, reference, beta = 1)$F
  return(f1)
}
```

# Hello there n_vaccines

```{r}
# subsetting the dataframe
subsetting <- function(data, choose_variant, choose_agegroup) {
  output <- data %>% 
    filter(
      variant_period == choose_variant
      & age_fct_60years == choose_agegroup
      # & n_vacunas_covid %in% c("Ninguna", choose_vacc)
      # & (ultima_inmun_infecc_bin == choose_time_since_vac | is.na(ultima_inmun_infecc_bin))
    ) %>% 
    mutate(across(
      c(variant_period, age_fct_60years), droplevels
    ))
  return(output)
}

variants <- c("Before α", "α", "Δ", "Ό")
agegroups <- c("Menor de 60 años", "60 años o más")
# vaccines <- c("Una", "Dos", "Tres")
# last_vacc <- c("Less than one month", "One to three months", "Three to six months", "Six months or more")

grid <- 
  expand_grid(variants, agegroups) %>% # vaccines, last_vacc
  mutate(
    across(c(variants, agegroups), ~word(.x, 1), .names = "primera_palabra_{.col}"),
    future_name = paste(
      primera_palabra_variants, 
      primera_palabra_agegroups, 
      # primera_palabra_vaccines, 
      # primera_palabra_last_vacc,
      sep = "_"
    )
  ) %>% 
  select(-starts_with("primera_palabra"))

subset_list <- list()

# Iterar a través de cada fila del dataframe de argumentos
for (i in 1:nrow(grid)) {
  # Obtener los argumentos para la función subsetting de la fila actual
  # choose_variant <- grid$variants[i]
  # chose_agegroup <- grid$agegroups[i]
  # choose_vacc <- grid$vaccines[i]
  # choose_time_since_vac <- grid$last_vacc[i]
  result_dataframe_name <- grid$future_name[i]
  # Llamar a la función subsetting con los argumentos actuales y guardar el resultado en un nuevo dataframe
  resultado <- 
    subsetting(
      data = estudio_vacunas_t_final_selected, 
      choose_variant = grid$variants[i],
      choose_agegroup = grid$agegroups[i]
      # choose_vacc = grid$vaccines[i],
      # choose_time_since_vac = grid$last_vacc[i]
    )
  # Asignar el dataframe resultante a un nombre utilizando el valor de 'result_dataframe_name'
  assign(result_dataframe_name, resultado)
  # Agregar el dataframe resultante a la lista de resultados
  subset_list[[result_dataframe_name]] <- resultado
}
# Verificar los nombres de los dataframes resultantes almacenados en la lista
print(names(subset_list))
```

# ESTA SECCION ERA PRUEBA, NO CORRER

```{r}
gam_hosp_stay_bin <- 
  gam(
    hosp_stay_bin ~ s(age, k = 4) 
    + n_vacunas_covid
    + desc_sexo 
    # + variant_period
    + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc 
    + hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca 
    + insuficiencia_renal_cronica + vih + cancer_hematologico + cancer_organo_solido 
    # + n_prev_infecc 
    + ultima_inmun_infecc_bin,
    data = subset_list[[3]],
    family = binomial()
  )

# Extract the model coefficients and their confidence intervals
coef_data <- data.frame(coef = coef(gam_hosp_stay_bin))
se <- sqrt(diag(vcov(gam_hosp_stay_bin)))
z_value <- qnorm(0.975)  # 95% confidence level (two-sided)

# Calculate the odds ratios and their respective lower and upper confidence limits
coef_data$OR <- exp(coef_data$coef)
coef_data$OR_lower <- exp(coef_data$coef - z_value * se)
coef_data$OR_upper <- exp(coef_data$coef + z_value * se)

# Calculate the p-values
p_values <- 2 * (1 - pnorm(abs(coef_data$coef) / se))
coef_data$p_value <- p_values

# Create a variable to store the predictor names
coef_data$predictor <- rownames(coef_data)
```

```{r}
# Fórmula para la regresión GAM
formula_gam_hosp <- 
  hosp_stay_bin ~ s(age, k = 4) + desc_sexo + 
  n_vacunas_covid + asma + cardiopatia_isquemica + cirrosis_hepatica + diabetes + epoc +
  hepatopatia_cronica_excepto_cirrosis + hipertension + insuficiencia_cardiaca + insuficiencia_renal_cronica +
  vih + cancer_hematologico + cancer_organo_solido + 
  ultima_inmun_infecc_bin

# Crear una lista para almacenar los resultados de los modelos GAM
results_list <- list()

# Bucle for para realizar la regresión GAM en cada dataframe de la lista
for (i in seq_along(subset_list)) {
  # Ajustar el modelo GAM para el dataframe i
  model <- gam(formula_gam_hosp, data = subset_list[[i]], family = binomial())
  
  # Extraer los coeficientes, intervalos de confianza y p-values
  coef_data <- data.frame(coef = coef(model))
  se <- sqrt(diag(vcov(model)))
  z_value <- qnorm(0.975)  # 95% confidence level (two-sided)
  coef_data$OR <- exp(coef_data$coef)
  coef_data$OR_lower <- exp(coef_data$coef - z_value * se)
  coef_data$OR_upper <- exp(coef_data$coef + z_value * se)
  p_values <- 2 * (1 - pnorm(abs(coef_data$coef) / se))
  coef_data$p_value <- p_values
  coef_data$predictor <- rownames(coef_data)
  
  result_dataframe_name <- names(subset_list)[[i]]
  
  assign(result_dataframe_name, coef_data)
  
  # Almacenar los resultados del modelo en la lista de resultados
  results_list[[result_dataframe_name]] <- coef_data
}
a <- results_list[[6]]
```






