---
title: "03b_tables_improved"
output: html_document
---

# Environment

```{r}
library(dplyr)
library(magrittr)
library(tableone)
library(kableExtra)
library(gtsummary)
library(rio)
library(purrr)
library(summarytools)
library(zoo)
library(lubridate)
library(vroom)
library(stringr)
library(stringi)
library(tidyr)
library(ggplot2)
library(parallel)
library(janitor)



estudio_vacunas_t_final_selected <- 
  readRDS("/opt/datos_compartidos/vacunas_data/Rfiles/estudio_vacunas_t_final_selected_manuscript.rds")



comorb_no_cancer <- estudio_vacunas_t_final_selected %>% 
  select(asma, cardiopatia_isquemica:diabetes, epoc:insuficiencia_renal_cronica, vih) %>% 
  colnames(.)

solid_cancers_vector <- estudio_vacunas_t_final_selected %>% 
  select(cancer_colorrectal:cancer_de_vejiga, melanoma_de_piel, sarcoma_de_kaposi) %>% 
  colnames(.)

hemat_cancers_vector <- estudio_vacunas_t_final_selected %>% 
  select(cancer_inmunoproliferativo, enfermedad_de_hodgkin, linfoma_no_hodgkin, leucemia) %>% 
  colnames(.)



estudio_vacunas_t_final_selected %<>% 
  mutate(
    variant_period = relevel(as.factor(variant_period), ref = "Dominance of Alpha variant"),
    across(comorb_no_cancer, ~if_else(.x == 1, "Sí", "No")),
    across(comorb_no_cancer, as.factor),
    across(comorb_no_cancer, ~relevel(.x, ref = "No")),
    across(c(hosp_stay_bin, icu_stay_bin), ~if_else(.x == 1, "Sí", "No")),
    across(c(hosp_stay_bin, icu_stay_bin), ~as.factor(.x)),
    across(c(hosp_stay_bin, icu_stay_bin), ~relevel(.x, ref = "No")),
  )
```

# Table 1

```{r}
str(estudio_vacunas_t_final_selected)



##############################################################################################################
# Description of total data

t1_total_age <- estudio_vacunas_t_final_selected %>%
  select(age) %>%
  tbl_summary(
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list(age ~ 2)
  )
t1_total_age

t1_total_categ <- estudio_vacunas_t_final_selected %>%
  select(where(is.factor)) %>%
  select(-c(mortality, mortality30d, hosp_stay_bin, icu_stay_bin)) %>% 
  tbl_summary(statistic = list(all_categorical() ~ "{n} ({p}%)"))
t1_total_categ



##############################################################################################################
# Description by hospital stay

t1_byhosp_age_hosp_duration <- estudio_vacunas_t_final_selected %>%
  select(hosp_stay_bin, age, estancia_hospitalaria_dias) %>%
  tbl_summary(
    by = hosp_stay_bin,
    statistic = list(
      age ~ "{mean} ({sd})",
      estancia_hospitalaria_dias ~ "{median} ({p25}, {p75})"
    ),
    digits = list(age ~ 2)
  )
  # add_p() %>% 
  # add_ci()
t1_byhosp_age_hosp_duration


t1_byhosp_categ <- estudio_vacunas_t_final_selected %>%
  select(where(is.factor)) %>%
  select(-c(mortality, mortality30d, icu_stay_bin)) %>% 
  tbl_summary(
    by = hosp_stay_bin,
    statistic = list(all_categorical() ~ "{n} ({p}%)")
    # digits = list(age ~ 2)
  )
  # add_p() %>% 
  # add_ci()
t1_byhosp_categ



##############################################################################################################
# Description by ICU stay

t1_byicu_age_icu_duration <- estudio_vacunas_t_final_selected %>%
  select(icu_stay_bin, age, estancia_hospitalaria_dias, num_dias_uci) %>%
  tbl_summary(
    by = icu_stay_bin,
    statistic = list(
      age ~ "{mean} ({sd})",
      estancia_hospitalaria_dias ~ "{median} ({p25}, {p75})",
      num_dias_uci ~ "{median} ({p25}, {p75})"
    ),
    digits = list(age ~ 2)
  )
  # add_p() %>% 
  # add_ci()
t1_byicu_age_icu_duration


t1_byicu_categ <- estudio_vacunas_t_final_selected %>%
  select(where(is.factor)) %>%
  select(-c(mortality, mortality30d, hosp_stay_bin)) %>% 
  tbl_summary(
    by = icu_stay_bin,
    statistic = list(all_categorical() ~ "{n} ({p}%)")
    # digits = list(age ~ 2)
  )
  # add_p() %>% 
  # add_ci()
t1_byicu_categ



##############################################################################################################
# Description by mortality at 30 days

t1_bymortality_age_icu_duration <- estudio_vacunas_t_final_selected %>%
  select(mortality30d, age, estancia_hospitalaria_dias, num_dias_uci) %>%
  tbl_summary(
    by = mortality30d,
    statistic = list(
      age ~ "{mean} ({sd})",
      estancia_hospitalaria_dias ~ "{median} ({p25}, {p75})",
      num_dias_uci ~ "{median} ({p25}, {p75})"
    ),
    digits = list(age ~ 2)
  )
  # add_p() %>% 
  # add_ci()
t1_bymortality_age_icu_duration


t1_bymortality_categ <- estudio_vacunas_t_final_selected %>%
  select(where(is.factor)) %>%
  select(-c(mortality, icu_stay_bin, hosp_stay_bin)) %>% 
  tbl_summary(
    by = mortality30d,
    statistic = list(all_categorical() ~ "{n} ({p}%)")
    # digits = list(age ~ 2)
  )
  # add_p() %>% 
  # add_ci()
t1_bymortality_categ
```


