---
title: "Figures"
output: html_document
---

# Environment

```{r setup, include=FALSE}
library(networkD3)
library(dplyr)
library(ggplot2)
library(janitor)
library(stringi)
library(lubridate)
```

# Upset Plot for describing categories

```{r cars}
upset(data=vacunas, intersections = NOM_VACUNA,group.by = COD_NUHSA_ENCRIPTADO, order.by = "freq")
```

# Sankey Plots

## Data Load

You can also embed plots, for example:

```{r}


# Read final dataset file 
estudio_vacunas_t_final_selected <-
  readRDS(file = "/opt/datos_compartidos/vacunas_data/Rfiles/estudio_vacunas_t_final_selected.rds")
nrow(estudio_vacunas_t_final_selected)
summary(estudio_vacunas_t_final_selected$pautas_covid)


# Vaccinated and unvaccinated population before positive CODIV-19 infection by RT-PCR
vacunados <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("1", "2", "3", "4")) %>%
  nrow()
vacunados

no_vacunados <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("0")) %>%
  nrow()
no_vacunados

# Hospital admission data
vacunados_ingresados <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("1", "2", "3", "4")
         & hosp_stay_bin == 1) %>%
  nrow()
vacunados_ingresados

vacunados_no_ingresados <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("1", "2", "3", "4")
         & hosp_stay_bin == 0) %>%
  nrow()
vacunados_no_ingresados

no_vacunados_ingresados <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("0")
         & hosp_stay_bin == 1) %>%
  nrow()
no_vacunados_ingresados

no_vacunados_no_ingresados <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("0")
         & hosp_stay_bin == 0) %>%
  nrow()
no_vacunados_no_ingresados


# UCI admission data
vacunados_ingresados_uci <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("1", "2", "3", "4")
         & icu_stay_bin == 1) %>%
  nrow()
vacunados_ingresados_uci

vacunados_no_ingresados_uci <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("1", "2", "3", "4")
         & icu_stay_bin == 0) %>%
  nrow()
vacunados_no_ingresados_uci

no_vacunados_ingresados_uci <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("0")
         & icu_stay_bin == 1) %>%
  nrow()
no_vacunados_ingresados_uci

no_vacunados_no_ingresados_uci <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("0")
         & icu_stay_bin == 0) %>%
  nrow()
no_vacunados_no_ingresados_uci


# Mortality data
vacunados_muertos <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("1", "2", "3", "4")
         & mortality30d == 1) %>%
  nrow()
vacunados_muertos

vacunados_vivos <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("1", "2", "3", "4")
         & mortality30d == 0) %>%
  nrow()
vacunados_vivos

no_vacunados_muertos <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("0")
         & mortality30d == 1) %>%
  nrow()
no_vacunados_muertos

no_vacunados_vivos <-
  estudio_vacunas_t_final_selected %>%
  filter(pautas_covid %in% c("0")
         & mortality30d == 0) %>%
  nrow()
no_vacunados_vivos

```
## Sankey Plot for Hospital Admission


```{r}
#Name of nodes
A <- "Poblaci칩n de estudio"
B <- "Vacunados"
C <- "No Vacunados"
D <- "No Hospitalizados"
E <- "Hospitalizados"

# Make a connection data frame
source <- c(A, A, B, B, C, C)
target <- c(B, C, D, E, D, E)
value <- c(vacunados, no_vacunados, vacunados_no_ingresados, vacunados_ingresados, no_vacunados_no_ingresados, no_vacunados_ingresados)
data <- data.frame(source, target, value)

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <-
  data.frame("name" = c(
    as.character(data$source),
    as.character(data$target)
    %>% unique()
  ))

# With networkD3, connection must be provided using id, not using real name like in the links dataframe. So we need to reformat it.
data$IDsource <- match(data$source, nodes$name) - 1
data$IDtarget <- match(data$target, nodes$name) - 1


## Add link types for coloring purpose
data$group = as.factor(c("type_0",
                         "type_0",
                         "type_1",
                         "type_2",
                         "type_1",
                         "type_2"))

# Add a 'group' column to each node.
nodes$group <-
  as.factor(
    c(
      "node1",
      "node1",
      "node2",
      "node2",
      "node3",
      "node3",
      "node2",
      "node3",
      "node4",
      "node5"
    )
  )

# Give a color for each group
my_color <-
  'd3.scaleOrdinal() .domain(["type_0", "type_1", "type_2", "node1", "node2", "node3", "node4", "node5"]) .range(["#a4b0be", "#7bed9f", "#ff6b81", "#747d8c", "#70a1ff", "#eccc68", "#2ed573", "#ff4757"])'

# Create the Sankey diagram
SankeyDiagram <- sankeyNetwork(
  Links = data,
  Nodes = nodes,
  Source = "IDsource",
  Target = "IDtarget",
  Value = "value",
  NodeID = "name",
  colourScale = my_color,
  LinkGroup = "group",
  NodeGroup = "group",
  fontSize = 16,
  fontFamily = 34,
  nodeWidth = 100,
  nodePadding = 20,
  height = 400,
  width = 1100,
  iterations = 32,
  sinksRight = FALSE
)

# Print the Sankey diagram
SankeyDiagram


```

## Sankey Plot for UCI Admission


```{r}
#Name of nodes
A <- "Poblaci칩n de estudio"
B <- "Vacunados"
C <- "No Vacunados"
G <- "No Ingresados en UCI"
H <- "Ingresados en UCI"

# Make a connection data frame
source <- c(A, A, B, B, C, C)
target <- c(B, C, G, H, G, H)
value <- c(vacunados, no_vacunados, vacunados_no_ingresados_uci, vacunados_ingresados_uci, no_vacunados_no_ingresados_uci, no_vacunados_ingresados_uci)
data <- data.frame(source, target, value)

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <-
  data.frame("name" = c(
    as.character(data$source),
    as.character(data$target)
    %>% unique()
  ))

# With networkD3, connection must be provided using id, not using real name like in the links dataframe. So we need to reformat it.
data$IDsource <- match(data$source, nodes$name) - 1
data$IDtarget <- match(data$target, nodes$name) - 1


## Add link types for coloring purpose
data$group = as.factor(c("type_0",
                         "type_0",
                         "type_1",
                         "type_2",
                         "type_1",
                         "type_2"))

# Add a 'group' column to each node.
nodes$group <-
  as.factor(
    c(
      "node1",
      "node1",
      "node2",
      "node2",
      "node3",
      "node3",
      "node2",
      "node3",
      "node4",
      "node5"
    )
  )

# Give a color for each group
my_color <-
  'd3.scaleOrdinal() .domain(["type_0", "type_1", "type_2", "node1", "node2", "node3", "node4", "node5"]) .range(["#a4b0be", "#7bed9f", "#ff6b81", "#747d8c", "#70a1ff", "#eccc68", "#2ed573", "#ff4757"])'

# Create the Sankey diagram
SankeyDiagram <- sankeyNetwork(
  Links = data,
  Nodes = nodes,
  Source = "IDsource",
  Target = "IDtarget",
  Value = "value",
  NodeID = "name",
  colourScale = my_color,
  LinkGroup = "group",
  NodeGroup = "group",
  fontSize = 16,
  fontFamily = 34,
  nodeWidth = 100,
  nodePadding = 20,
  height = 400,
  width = 1100,
  iterations = 32,
  sinksRight = FALSE
)

# Print the Sankey diagram
SankeyDiagram

```

## Sankey Plot for Survival/Mortality


```{r}
#Name of nodes
A <- "Poblaci칩n de estudio"
B <- "Vacunados"
C <- "No Vacunados"
I <- "Supervivientes"
J <- "Fallecidos"

# Make a connection data frame
source <- c(A, A, B, B, C, C)
target <- c(B, C, I, J, I, J)
value <- c(vacunados, no_vacunados, vacunados_vivos, vacunados_muertos, no_vacunados_vivos, no_vacunados_muertos)
data <- data.frame(source, target, value)

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <-
  data.frame("name" = c(
    as.character(data$source),
    as.character(data$target)
    %>% unique()
  ))

# With networkD3, connection must be provided using id, not using real name like in the links dataframe. So we need to reformat it.
data$IDsource <- match(data$source, nodes$name) - 1
data$IDtarget <- match(data$target, nodes$name) - 1


## Add link types for coloring purpose
data$group = as.factor(c("type_0",
                         "type_0",
                         "type_1",
                         "type_2",
                         "type_1",
                         "type_2"))

# Add a 'group' column to each node.
nodes$group <-
  as.factor(
    c(
      "node1",
      "node1",
      "node2",
      "node2",
      "node3",
      "node3",
      "node2",
      "node3",
      "node4",
      "node5"
    )
  )

# Give a color for each group
my_color <-
  'd3.scaleOrdinal() .domain(["type_0", "type_1", "type_2", "node1", "node2", "node3", "node4", "node5"]) .range(["#a4b0be", "#7bed9f", "#ff6b81", "#747d8c", "#70a1ff", "#eccc68", "#2ed573", "#ff4757"])'

# Create the Sankey diagram
SankeyDiagram <- sankeyNetwork(
  Links = data,
  Nodes = nodes,
  Source = "IDsource",
  Target = "IDtarget",
  Value = "value",
  NodeID = "name",
  colourScale = my_color,
  LinkGroup = "group",
  NodeGroup = "group",
  fontSize = 16,
  fontFamily = 34,
  nodeWidth = 100,
  nodePadding = 20,
  height = 400,
  width = 1100,
  iterations = 32,
  sinksRight = FALSE
)

# Print the Sankey diagram
SankeyDiagram
```


# Rentabilidad Edad

```{r}
# Definir los par치metros
costo_hospitalizacion <- 4612.76
precio_vacuna <- 31
dosis_equiv <- 148
nnt <- 148
red_abs_riesgo <- 0.0068

# Definir un vector de edades de 18 a 120
edades <- 18:120

# Calcular la rentabilidad para cada edad
rentabilidad <- (costo_hospitalizacion/dosis_equiv) / nnt / (1 - red_abs_riesgo)

# Crear un dataframe con los resultados
df <- data.frame(edad = edades, rentabilidad = rentabilidad)

```

