---
title: "parte_alvaro"
output: html_document
---

# Environment

```{r}
library(data.table)
library(summarytools)
library(zoo)
library(dplyr)
library(magrittr)
library(lubridate)

# defining functions

special_date = function(number){
  date = if_else(number%in%c(-1,0,NA), as.Date(NA), as.Date(as.character(number),format="%Y%m%d"))
  return(date)
}
```

# Data Load

## poblacion_diana

? jaime Cordero

## Pupa

Miguel transformar.

## resultados_pruebas_COVID

* Álvaro

```{r RESULTADOS_PRUEBAS_COVID}

# '_t' means total population, second data load

# database importation and tidying
resultados_pruebas_COVID_t <-
  fread("/opt/datos_compartidos/vacunas_data/total/ENC_VACUNAS_TEST_COVID.txt",
        header = T,
        encoding = 'UTF-8') %>% 
  as.data.frame() %>% 
  rename(COD_NUHSA_ENCRIPTADO = NUHSA_ENCRIPTADO) %>% 
  select(-TIPO_PRUEBA) %>% 
  mutate(FECHA_MUESTRA = as.Date(as.character(FECHA_MUESTRA),
                                 format = "%d/%m/%Y"))

# infection count per person
infect_COVID_num <-
  resultados_pruebas_COVID_t %>%
  group_by(COD_NUHSA_ENCRIPTADO) %>%
  summarise(infecc_covid = n())

# first COVID infection with date available
infect_COVID_first <-
  resultados_pruebas_COVID_t %>%
  group_by(COD_NUHSA_ENCRIPTADO) %>%
  filter(row_number() == 1 & DESC_T_PRUEBA == 'PCR' & !is.na(FECHA_MUESTRA)) %>% 
  rename(infect_COVID_first_date = FECHA_MUESTRA) %>%
  select(COD_NUHSA_ENCRIPTADO, infect_COVID_first_date)
```

## episodios_cmbd

 * Rafa

## vacunas

Jaime M

## periodos pandemicos ?